name: CI

on:
  push:      
  workflow_dispatch:

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-20.04

    steps:
      - name: branch checkout
        uses: actions/checkout@v3   

      - run: ls -al /home/runner/work/Oxla/Oxla/.github/workflows/

      - name: setup toolchain
        uses: ./.github/workflows/setup-toolchain.yml
