name: build

on:
  push:      
  pull_request: 
    types: [opened, ready_for_review]  
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: always run
        run: echo PR checking in progress!
          
      - name: print cache hit
        run: |
          echo runs on branch: \"${{github.ref_name}}\", on \"${{ github.event_name }}\"
          echo bazel-cache hit: ${{ steps.bazel-cache.outputs.cache-hit == 'true' }}
  
