name: build

on:
  push:      
    branches:
      - main
  pull_request: 
    types: [opened, ready_for_review]  
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    if: ${{github.event.pull_request.draft == false}}

    steps:
      - uses: actions/checkout@v3
      
      - name: always run
        run: echo PR checking in progress!
          
      - name: print triggering event
        run: |
          echo runs on branch: \"${{github.ref_name}}\", on \"${{ github.event_name }}\"
          echo is pull request a draft? ${{github.event.pull_request.draft == true}}
          
      - name: fail if main
        if: github.ref_name == 'main'
        run: exit 1  
