name: CI workflow

on:
  pull_request: 
    types: [opened, ready_for_review, closed]  

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run always
        run: echo workflow is working!

      - name: Run if merge
        if: github.event.pull_request.merged == 'true'
        run: |
          echo pull request: merge is about to be prevented!
          exit 1
        
      - name: Run if push
        if: github.event_name == 'push'
        run: echo commit pushed!
