name: MasterBuildCheck

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      
      - name: always run
        run: echo master check is working!

      - name: check master branch
        run: |
          echo pull request: merge is about to be prevented!
          exit 1
