name: PRBuildCheck

on:
  push:
  pull_request: 
    types: [opened, ready_for_review]  

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: always run
        run: echo PR checking in progress!
        
      - name: Run if push
        if: github.event_name == 'push'
        run: echo commit pushed!
